# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/azure-appservice-static
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run:
          name: NPM Test
          command: npm test

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ];
              then ./scripts/publish.sh production;
            fi

            ./scripts/publish.sh
            #!/bin/bash
            git config --global user.email "$USER_EMAIL"
            git config --global user.name "$USER_NAME"

            git checkout -b "$1"
            git merge master
            git commit -am "$CIRCLE_BRANCH build#$CIRCLE_BUILD_NUM"
            git push --force --set-upstream origin $1